# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeGCD <- function(a, b) {
    .Call('cgeom_computeGCD', PACKAGE = 'cgeom', a, b)
}

computeLCM <- function(a, b) {
    .Call('cgeom_computeLCM', PACKAGE = 'cgeom', a, b)
}

