# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Boilerplate Rcpp.  
#' 
#' Plate boiler. 
#' @param a number
#' @return b nice
#' @export
#' @examples
#' \dontrun{
#' a <- 6
#' b <- 15
#' cat( c(computeGCD(a,b), computeLCM(a,b)), "\n")
computeGCD <- function(a, b) {
    .Call('cgeom_computeGCD', PACKAGE = 'cgeom', a, b)
}

#' Boilerplate Rcpp.  
#' 
#' Plate boiler. 
#' @param a number
#' @return b nice
#' @export
#' @examples
#' \dontrun{
#' a <- 6
#' b <- 15
#' cat( c(computeGCD(a,b), computeLCM(a,b)), "\n")
computeLCM <- function(a, b) {
    .Call('cgeom_computeLCM', PACKAGE = 'cgeom', a, b)
}

